/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meizu_powertesttool_phonemonitor_HelloJni */

#ifndef _Included_com_meizu_powertesttool_phonemonitor_HelloJni
#define _Included_com_meizu_powertesttool_phonemonitor_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meizu_powertesttool_phonemonitor_HelloJni
 * Method:    helloJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_meizu_powertesttool_phonemonitor_HelloJni_helloJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
